import React, { Component } from 'react'

import { Row, Col, Card, Icon } from 'antd'

const arrow = [
  'step-backward',
  'step-forward',
  'fast-backward',
  'fast-forward',
  'shrink',
  'arrow-salt',
  'caret-down',
  'caret-left',
  'caret-up',
  'caret-right',
  'caret-circle-right',
  'caret-circle-left',
  'caret-circle-o-right',
  'caret-circle-o-left',
  'circle-right',
  'circle-left',
  'circle-o-right',
  'circle-o-left',
  'double-right',
  'double-left',
  'verticle-right',
  'verticle-left',
  'forward',
  'backward',
  'rollback',
  'retweet',
  'right',
  'down',
  'up',
  'question',
  'plus',
  'pause',
  'minus',
  'info-circle',
  'exclamation',
  'cross',
  'check',
  'lock',
  'android',
  'apple',
  'area-chart',
  'bar-chart',
  'bars',
  'book',
  'calendar',
  'code',
  'copy',
  'credit-card',
  'delete',
  'desktop',
  'download-line',
  'edit',
  'ellipsis',
  'environment',
  'file',
  'folder',
  'github',
  'hdd',
  'frown',
  'meh',
  'inbox',
  'laptop',
  'large',
  'line-chart',
  'link',
  'logout',
  'mail',
  'mobile',
  'paper-clip',
  'picture',
  'pie-chart',
  'poweroff',
  'reload',
  'search',
  'setting',
  'share-alt',
  'shopping-cart',
  'smile',
  'tablet',
  'tag',
  'tags',
  'to-top',
  'unlock',
  'upload',
  'user',
  'video-camera',
  'windows',
  'loading',
]

export default class IconComponent extends Component {
  render() {
    return arrow.map(item => (
      <Col key={item} lg={6} md={12}>
        <Icon type={item} />
      </Col>
    ))
  }
}
